server:
  port: 9091
eureka:
  instance:
    instanceId: customer-${random.int}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 10
  client:
    region: default
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
management:
  security:
    enabled: false